// src/renderer/player/player.tsx
import { FORWARD, BACKWARD, APP_NAME } from "../../constants";
import {appStateReducer, initialAppState} from "./appStateReducer";
import { handleShortcut } from "../shortcut";
import { useCallback, useEffect, useReducer, useRef } from "react";
import { Footer } from "./footer";
import icon from "../../assets/icon.ico"

const Buttons = {
    left:0,
    right:2,
}

const Player = () => {

    const [appState, dispatchAppState] = useReducer(appStateReducer, initialAppState);
    const video = useRef<HTMLVideoElement>(null)
    const viewport = useRef<HTMLDivElement>(null)
    const container = useRef<HTMLDivElement>(null)
    const hideControlTimeout = useRef<number | null>(null);

    const updateTime = useCallback((progress:number) => {

        if(!video.current) return;

        video.current.currentTime = appState.media.videoDuration * progress;

    },[video, appState.media.videoDuration])

    const onTimeUpdate = () => {

        if(!video.current) return;

        const duration = appState.media.videoDuration > 0 ? appState.media.videoDuration : 1

        dispatchAppState({type:"currentTime", value:video.current.currentTime})

        window.api.send("progress", {progress:video.current.currentTime / duration})
    }

    const updateVolume = useCallback((volume:number) => {

        if(volume > 1 || volume < 0 || !video.current) return;

        video.current.volume = volume
        dispatchAppState({type:"videoVolume", value:volume})

    },[video])

    const createGain = useCallback(() => {

        if(!video.current) throw new Error("Media not found");

        if(appState.media.gainNode) return appState.media.gainNode;

        const audioCtx = new AudioContext();
        const source = audioCtx.createMediaElementSource(video.current);
        const gainNode = audioCtx.createGain();

        dispatchAppState({type:"gainNode", value:gainNode})

        source.connect(gainNode);
        gainNode.connect(audioCtx.destination);

        return gainNode;

    },[appState.media.gainNode])

    const updateAmpLevel = useCallback((ampLevel:number) => {

        if(ampLevel > 1 || ampLevel < 0) return;

        const gainNode = createGain();

        dispatchAppState({type:"ampLevel", value:ampLevel})

        gainNode.gain.value = ampLevel * 10;


    },[createGain])

    const onFileDrop = (e:React.DragEvent) => {

        e.preventDefault();

        const items = e.dataTransfer ? e.dataTransfer.items : []

        const dropItems = Array.from(items).filter(item => {
            return item.kind === "file" && (item.type.includes("video") || item.type.includes("audio"));
        })

        if(dropItems.length){
            const files = dropItems.map(item => item.getAsFile()?.path ?? "")
            window.api.send("drop", {files, renderer:"Player"})
        }
    }

    const initPlayer = useCallback(() => {

        dispatchAppState({type:"currentFile", value:null})
        dispatchAppState({type:"videoDuration", value:0})
        dispatchAppState({type:"playing", value:false})
        dispatchAppState({type:"currentTime", value:0})
        viewport.current?.classList.remove("loaded");
        video.current?.load();

    },[video, viewport])

    const beforeDelete = useCallback((data:Mp.ReleaseFileRequest) => {

        if(data.fileIds.includes(appState.currentFile.id)){
            dispatchAppState({type:"currentFile", value:null})
        }
        window.api.send("file-released", {fileIds:data.fileIds})

    },[appState.currentFile.id]);

    const loadMedia = useCallback((e:Mp.FileLoadEvent) => {

        if(!video.current) return;

        dispatchAppState({type:"currentFile", value:e.currentFile})
        video.current.autoplay = e.autoPlay ? e.autoPlay : appState.playing;
        video.current.muted = appState.media.mute;
        video.current.playbackRate = appState.media.playbackSpeed
        video.current.load();

    },[video, appState.media.mute, appState.media.playbackSpeed, appState.playing])

    const onMediaLoaded = () => {

        document.title = `${APP_NAME} - ${appState.currentFile.name}`

        changeVideoSize();

        dispatchAppState({type:"videoDuration", value:video.current?.duration ?? 0})

        dispatchAppState({type:"currentTime", value:video.current?.currentTime ?? 0})

        viewport.current?.classList.add("loaded");

        if(video.current){
            video.current.autoplay = false;
        }
    }

    const changeVideoSize = useCallback((config?:Mp.Config) => {

        if(!video.current || !container.current) return;

        const fitToWindow = config ? config.video.fitToWindow : appState.media.fitToWindow
        const containerRect = container.current.getBoundingClientRect();

        if(fitToWindow && containerRect.height > video.current.videoHeight){
            const ratio = Math.min(containerRect.width / video.current.videoWidth, containerRect.height / video.current.videoHeight);
            video.current.style.height = `${video.current.videoHeight * ratio}px`
        }else{
            video.current.style.height = ""
        }

    },[video, appState.media.fitToWindow])

    const changeCurrentTime = useCallback((time:number) => {

        if(!video.current) return;

        const nextTime = video.current.currentTime + time;

        if(nextTime >= video.current.duration){
            return changeFile(FORWARD)
        }

        if(nextTime < 0){
            return changeFile(BACKWARD)
        }

        video.current.currentTime = nextTime;

    },[video])

    const playFoward = useCallback((button:number) => {

        if(!appState.loaded) return;

        if(button === 0){
            changeCurrentTime(appState.media.seekSpeed);
        }

        if(button === 2){
            changeFile(FORWARD)
        }

    },[appState.loaded, appState.media.seekSpeed, changeCurrentTime])

    const playBackward = useCallback((button:number) => {

        if(!appState.loaded) return;

        if(button === 0){
            changeCurrentTime(-appState.media.seekSpeed)
        }

        if(button === 2){
            changeFile(BACKWARD)
        }

    },[appState.loaded, appState.media.seekSpeed, changeCurrentTime])

    const changeFile = (index:number) => {
        return window.api.send("load-file", {index, isAbsolute:false})
    }

    const togglePlay = useCallback(() => {

        if(!appState.loaded || !video.current) return;

        if(video.current.paused){
            video.current.play();
        }else{
            video.current.pause();
        }

    },[appState.loaded])

    const onPlayed = () => {
        window.api.send("play-status-change", {status:"playing"})
        dispatchAppState({type:"playing", value:true})
    }

    const onPaused = () => {

        if(!video.current) return;

        if(video.current.currentTime == video.current.duration) return;

        window.api.send("play-status-change", {status:"paused"})
        dispatchAppState({type:"playing", value:false})
    }

    const stop = useCallback(() => {

        if(!appState.loaded || !video.current) return;

        window.api.send("play-status-change", {status:"stopped"})
        dispatchAppState({type:"playing", value:false})
        video.current.load();

    },[appState.loaded])

    const requestPIP = useCallback(async () => {

        if(video.current && appState.loaded){
            await video.current.requestPictureInPicture();
        }

    },[appState.loaded])

    const changePlaybackSpeed = useCallback((data:Mp.ChangePlaybackSpeedRequest) => {

        dispatchAppState({type:"playbackSpeed", value:data.playbackSpeed})
        if(video.current){
            video.current.playbackRate = data.playbackSpeed
        }

    },[video])

    const changeSeekSpeed = (data:Mp.ChangeSeekSpeedRequest) => {
        dispatchAppState({type:"seekSpeed", value:data.seekSpeed})
    }

    const captureMedia = useCallback(() => {

        if(!video.current || !appState.loaded) return;

        const canvas = document.createElement("canvas");
        const rect = video.current.getBoundingClientRect();
        canvas.width = rect.width;
        canvas.height = rect.height;

        const context = canvas.getContext("2d");
        if(context){
            context.drawImage(video.current, 0, 0, rect.width, rect.height);
        }
        const image = canvas.toDataURL("image/jpeg").replace(/^data:image\/jpeg;base64,/, "");

        window.api.send("save-capture", {data:image, timestamp:video.current.currentTime})

    },[appState.loaded])

    const toggleMute = useCallback(() => {

        dispatchAppState({type:"mute", value:!appState.media.mute})

    },[appState.media.mute])

    const minimize = () => {
        window.api.send("minimize", {})
    }

    const toggleMaximize = useCallback(() => {

        window.api.send("toggle-maximize", {})
        dispatchAppState({type:"isMaximized", value:!appState.isMaximized})

    },[appState.isMaximized])

    const onWindowSizeChanged = (e:Mp.ConfigChangeEvent) => {
        dispatchAppState({type:"isMaximized", value:e.config.isMaximized})
    }

    const hideControl = useCallback(() => {

        hideControlTimeout.current = window.setTimeout(() => {
            viewport.current?.classList.add("autohide")
        },2000)

    },[viewport])

    const exitFullscreen = useCallback(() => {

        dispatchAppState({type:"isFullScreen", value:false})

        if(hideControlTimeout.current){
            window.clearTimeout(hideControlTimeout.current)
        }
        viewport.current?.classList.remove("autohide")
        window.api.send("toggle-fullscreen", {fullscreen:false})

    },[viewport])

    const enterFullscreen = useCallback(() => {

        dispatchAppState({type:"isFullScreen", value:true})
        hideControl()
        window.api.send("toggle-fullscreen", {fullscreen:true})

    },[hideControl])

    const toggleFullscreen = useCallback(() => {

        if(appState.isFullScreen){
            exitFullscreen()
        }else{
            enterFullscreen()
        }

    },[appState.isFullScreen, enterFullscreen, exitFullscreen])

    const showControl = useCallback(() => {

        if(appState.isFullScreen){
            viewport.current?.classList.remove("autohide")
            if(hideControlTimeout.current) window.clearTimeout(hideControlTimeout.current)
            hideControl();
        }

    },[viewport, appState.isFullScreen, hideControl])

    const toggleConvert = () => {
        dispatchAppState({type:"converting"})
    }

    const onChangeDisplayMode = useCallback((e:Mp.ConfigChangeEvent) => {

        dispatchAppState({type:"fitToWindow", value:e.config.video.fitToWindow})
        changeVideoSize(e.config);

    },[changeVideoSize])

    const close = useCallback(() => {

        window.api.send("close", {mediaState:appState.media});

    },[appState.media])

    const prepare = useCallback((e:Mp.ReadyEvent) => {

        dispatchAppState({type:"isMaximized", value:e.config.isMaximized})

        updateVolume(e.config.audio.volume);
        updateAmpLevel(e.config.audio.ampLevel)

        dispatchAppState({type:"mute", value:e.config.audio.mute})

        dispatchAppState({type:"fitToWindow", value:e.config.video.fitToWindow})
        dispatchAppState({type:"playbackSpeed", value:e.config.video.playbackSpeed})
        dispatchAppState({type:"seekSpeed", value:e.config.video.seekSpeed})

        initPlayer();

    },[updateVolume, updateAmpLevel, initPlayer])

    const load = useCallback((e:Mp.FileLoadEvent) => {

        if(e.currentFile.id){
            loadMedia(e)
        }else{
            initPlayer();
        }

    },[initPlayer, loadMedia])

    const onMousemove = useCallback(() => {

        showControl();

    },[showControl]);

    const onKeydown = useCallback((e:KeyboardEvent) => {

        if(e.ctrlKey && e.key === "r") e.preventDefault();

        if(e.key === "F5") return window.api.send("reload", {});

        if(e.key === "ArrowRight"){

            showControl();

            if(e.shiftKey){
                changeCurrentTime(appState.media.seekSpeed)
            }else{
                playFoward(Buttons.left);
            }

            return
        }

        if(e.key === "ArrowLeft"){

            showControl();

            if(e.shiftKey){
                changeCurrentTime(-appState.media.seekSpeed)
            }else{
                playBackward(Buttons.left);
            }

            return
        }

        if(e.key === "ArrowUp"){
            showControl();
            updateVolume(appState.media.videoVolume + 0.01)
            return
        }

        if(e.key === "ArrowDown"){
            showControl();
            updateVolume(appState.media.videoVolume - 0.01)
            return
        }

        if(e.key === "Escape"){
            return exitFullscreen();
        }

        if(e.ctrlKey && e.key === "m"){
            return toggleMute();
        }

        if(e.key === "Enter"){
            return togglePlay();
        }

        return handleShortcut("Player", e);

    },[appState.media.seekSpeed, appState.media.videoVolume, changeCurrentTime, toggleMute, exitFullscreen, playBackward, playFoward, showControl, togglePlay, updateVolume]);

    const onResize = useCallback(() => {

        changeVideoSize()

    },[changeVideoSize]);

    const onContextMenu = (e:React.MouseEvent) => {
        e.preventDefault()
        e.stopPropagation()
        window.api.send("open-player-context", {})
    }

    useEffect(() => {

        window.api.receive("ready", prepare)
        window.api.receive("after-file-load", load)
        window.api.receive("toggle-play", togglePlay)
        window.api.receive("change-display-mode", onChangeDisplayMode)
        window.api.receive("restart", initPlayer)
        window.api.receive("release-file", beforeDelete)
        window.api.receive("after-toggle-maximize", onWindowSizeChanged)
        window.api.receive("toggle-convert", toggleConvert)
        window.api.receive("change-playback-speed", changePlaybackSpeed)
        window.api.receive("change-seek-speed", changeSeekSpeed);
        window.api.receive("toggle-fullscreen", toggleFullscreen)
        window.api.receive("capture-media", captureMedia)
        window.api.receive("picture-in-picture", requestPIP)
        window.api.receive("log", data => console.log(data.log))

        window.addEventListener("keydown", onKeydown)
        window.addEventListener("resize", onResize)

        document.addEventListener("mousemove", onMousemove)

        return () => {

            window.removeEventListener("keydown", onKeydown)
            window.removeEventListener("resize", onResize)

            document.removeEventListener("mousemove", onMousemove)

            window.api.removeAllListeners("ready")
            window.api.removeAllListeners("after-file-load")
            window.api.removeAllListeners("toggle-play")
            window.api.removeAllListeners("change-display-mode")
            window.api.removeAllListeners("restart")
            window.api.removeAllListeners("release-file")
            window.api.removeAllListeners("after-toggle-maximize")
            window.api.removeAllListeners("toggle-convert")
            window.api.removeAllListeners("change-playback-speed")
            window.api.removeAllListeners("change-seek-speed")
            window.api.removeAllListeners("toggle-fullscreen")
            window.api.removeAllListeners("capture-media")
            window.api.removeAllListeners("picture-in-picture")
            window.api.removeAllListeners("log")
        }
    },[beforeDelete, captureMedia, changePlaybackSpeed, initPlayer, load, onChangeDisplayMode, onKeydown, onMousemove, onResize, prepare, requestPIP, toggleFullscreen, togglePlay])

    return (
        <div ref={viewport} className={`viewport ${appState.isFullScreen ? "full-screen" : ""}`}>

            <div className="title-bar">
                <div className="icon-area">
                    <img className="ico" src={icon}/>
                    <span>{APP_NAME}</span>
                </div>
                <div className="title">{appState.currentFile.name}</div>
                <div className="window-area">
                    <div className="minimize" onClick={minimize}>&minus;</div>
                    <div className="maximize" onClick={toggleMaximize}><div className={appState.isMaximized ? "minbtn" : "maxbtn"}></div></div>
                    <div className="close" onClick={close}>&times;</div>
                </div>
            </div>

            <div ref={container} className="video-container media" onDragOver={e => e.preventDefault() } onDrop={onFileDrop} onDoubleClick={togglePlay} onContextMenu={onContextMenu}>
                <video
                    ref={video}
                    className="video media"
                    src={ appState.currentFile.src}
                    onCanPlayThrough={onMediaLoaded}
                    onEnded={() => changeFile(FORWARD)}
                    onTimeUpdate={onTimeUpdate}
                    onPlay={onPlayed}
                    onPause={onPaused}
                    onContextMenu={onContextMenu}
                    muted={appState.media.mute}
                />
            </div>

            <Footer
                playing={appState.playing}
                converting={appState.converting}
                media={appState.media}
                onMouseEnter={showControl}
                onUpdateTime={updateTime}
                onUpdateVolume={updateVolume}
                onUpdateAmpLevel={updateAmpLevel}
                onClickPlay={togglePlay}
                onClickStop={stop}
                onClickPrevious={playBackward}
                onClickNext={playFoward}
                onClickMute={toggleMute}
            />

        </div>
    )
}

export default Player;

// src/renderer/player/Player.svelte
<script lang="ts">

    import { onMount } from "svelte";
    import { appState, dispatch } from "./appStateReducer";
    import { useTranslation } from "../../translation/useTranslation"

    import { FORWARD, BACKWARD, APP_NAME, handleKeyEvent } from "../../constants";
    import { handleShortcut } from "../shortcut";
    import Footer from "./Footer.svelte";
    import icon from "../../assets/icon.ico"

    let video:HTMLVideoElement
    let container:HTMLDivElement
    let hideControlTimeout:number | null
    let lang:Mp.Lang = "en";

    const Buttons = {
        left:0,
        right:2,
    }

    const t = useTranslation(lang);

    const updateTime = (progress:number) => {

        if(!$appState.loaded) return;

        video.currentTime = $appState.media.videoDuration * progress;

    }

    const onTimeUpdate = () => {

        if(!$appState.loaded) return;

        const duration = $appState.media.videoDuration > 0 ? $appState.media.videoDuration : 1

        dispatch({type:"currentTime", value:video.currentTime})

        window.api.send("progress", {progress:video.currentTime / duration})
    }

    const updateVolume = (volume:number) => {

        if(volume > 1 || volume < 0) return;

        video.volume = volume
        dispatch({type:"videoVolume", value:volume})

    }

    const getGainNode = () => {

        if(!video) throw new Error("Media not found");

        if($appState.media.gainNode) return $appState.media.gainNode;

        const audioCtx = new AudioContext();
        const source = audioCtx.createMediaElementSource(video);
        const gainNode = audioCtx.createGain();

        dispatch({type:"gainNode", value:gainNode})

        source.connect(gainNode);
        gainNode.connect(audioCtx.destination);

        return gainNode;

    }

    const updateAmpLevel = (ampLevel:number) => {

        if(ampLevel > 1 || ampLevel < 0) return;

        const gainNode = getGainNode();

        dispatch({type:"ampLevel", value:ampLevel})

        gainNode.gain.value = ampLevel * 10;

    }

    const onFileDrop = (e:DragEvent) => {

        e.preventDefault();

        const items = e.dataTransfer ? e.dataTransfer.items : []

        const dropItems = Array.from(items).filter(item => {
            return item.kind === "file" && (item.type.includes("video") || item.type.includes("audio"));
        })

        if(dropItems.length){
            const files = dropItems.map(item => item.getAsFile()?.path ?? "")
            window.api.send("drop", {files, renderer:"Player"})
        }
    }

    const initPlayer = () => {

        dispatch({type:"currentFile", value:null})
        dispatch({type:"videoDuration", value:0})
        dispatch({type:"playing", value:false})
        dispatch({type:"currentTime", value:0})
        dispatch({type:"loaded", value:false})
        video.load();

    }

    const beforeDelete = (data:Mp.TrashRequest) => {

        if(data.fileIds.includes($appState.currentFile.id)){
            dispatch({type:"currentFile", value:null})
        }
        window.api.send("trash-ready", {fileIds:data.fileIds})

    };

    const beforeRename = (data:Mp.RenameRequest) => {

        if($appState.currentFile.id == data.id){
            data.currentTime = $appState.media.currentTime;
            dispatch({type:"currentFile", value:null})
        }
        window.api.send("rename-ready", data)
    }

    const loadMedia = (e:Mp.FileLoadEvent) => {

        dispatch({type:"currentFile", value:e.currentFile})

        video.autoplay = e.autoPlay ? e.autoPlay : $appState.playing;
        video.muted = $appState.media.mute;
        video.playbackRate = $appState.media.playbackSpeed
        dispatch({type:"currentTime", value:0})
        dispatch({type:"startFrom", value:e.startFrom})

        video.load();

    }

    const onMediaLoaded = () => {

        dispatch({type:"loaded", value:true})

        document.title = `${APP_NAME} - ${$appState.currentFile.name}`

        changeVideoSize();

        dispatch({type:"videoDuration", value:video.duration})

        if($appState.startFrom){
            changeCurrentTime($appState.startFrom)
        }

        video.autoplay = false;

    }

    const changeVideoSize = (config?:Mp.Config) => {

        const fitToWindow = config ? config.video.fitToWindow : $appState.media.fitToWindow
        const containerRect = container.getBoundingClientRect();

        if(fitToWindow && containerRect.height > video.videoHeight){
            const ratio = Math.min(containerRect.width / video.videoWidth, containerRect.height / video.videoHeight);
            video.style.height = `${video.videoHeight * ratio}px`
        }else{
            video.style.height = ""
        }

    }

    const changeCurrentTime = (time:number) => {

        if(!$appState.loaded) return;

        const nextTime = video.currentTime + time;

        if(nextTime >= video.duration){
            return changeFile(FORWARD)
        }

        if(nextTime < 0){
            return changeFile(BACKWARD)
        }

        video.currentTime = nextTime;

    }

    const playFoward = (button:number) => {

        if(!$appState.loaded) return;

        if(button === 0){
            changeCurrentTime($appState.media.seekSpeed);
        }

        if(button === 2){
            changeFile(FORWARD)
        }

    }

    const playBackward = (button:number) => {

        if(!$appState.loaded) return;

        if(button === 0){
            changeCurrentTime(-$appState.media.seekSpeed)
        }

        if(button === 2){
            changeFile(BACKWARD)
        }

    }

    const changeFile = (index:number) => {
        return window.api.send("load-file", {index, isAbsolute:false})
    }

    const togglePlay = () => {

        if(!$appState.loaded) return;

        if(video.paused){
            video.play();
        }else{
            video.pause();
        }

    }

    const onPlayed = () => {
        window.api.send("play-status-change", {status:"playing"})
        dispatch({type:"playing", value:true})
    }

    const onPaused = () => {

        if(video.currentTime == video.duration) return;

        window.api.send("play-status-change", {status:"paused"})
        dispatch({type:"playing", value:false})
    }

    const stop = () => {

        if(!$appState.loaded) return;

        window.api.send("play-status-change", {status:"stopped"})
        dispatch({type:"playing", value:false})
        video.load();

    }

    const requestPIP = async () => {
        if($appState.loaded){
            await video.requestPictureInPicture();
        }
    }

    const changePlaybackSpeed = (data:Mp.ChangePlaybackSpeedRequest) => {
        dispatch({type:"playbackSpeed", value:data.playbackSpeed})
        video.playbackRate = data.playbackSpeed
    }

    const changeSeekSpeed = (data:Mp.ChangeSeekSpeedRequest) => {
        dispatch({type:"seekSpeed", value:data.seekSpeed})
    }

    const captureMedia = () => {

        if(!$appState.loaded) return;

        const canvas = document.createElement("canvas");
        const rect = video.getBoundingClientRect();
        canvas.width = rect.width;
        canvas.height = rect.height;

        const context = canvas.getContext("2d");
        if(context){
            context.drawImage(video, 0, 0, rect.width, rect.height);
        }
        const image = canvas.toDataURL("image/jpeg").replace(/^data:image\/jpeg;base64,/, "");

        window.api.send("save-capture", {data:image, timestamp:video.currentTime})

    }

    const toggleMute = () => {
        dispatch({type:"mute", value:!$appState.media.mute})
    }

    const minimize = () => {
        window.api.send("minimize", {})
    }

    const toggleMaximize = () => {
        window.api.send("toggle-maximize", {})
        dispatch({type:"isMaximized", value:!$appState.isMaximized})
    }

    const onWindowSizeChanged = (e:Mp.ConfigChangeEvent) => {
        dispatch({type:"isMaximized", value:e.config.isMaximized})
    }

    const hideControl = () => {
        hideControlTimeout = window.setTimeout(() => {
            dispatch({type:"autohide", value:true})
        },2000)
    }

    const exitFullscreen = () => {

        dispatch({type:"isFullScreen", value:false})

        if(hideControlTimeout){
            window.clearTimeout(hideControlTimeout)
        }
        dispatch({type:"autohide", value:false})
        window.api.send("toggle-fullscreen", {fullscreen:false})

    }

    const enterFullscreen = () => {
        dispatch({type:"isFullScreen", value:true})
        hideControl()
        window.api.send("toggle-fullscreen", {fullscreen:true})
    }

    const toggleFullscreen = () => {
        if($appState.isFullScreen){
            exitFullscreen()
        }else{
            enterFullscreen()
        }
    }

    const showControl = () => {

        if($appState.isFullScreen){
            dispatch({type:"autohide", value:false})
            if(hideControlTimeout){
                window.clearTimeout(hideControlTimeout)
            }
            hideControl();
        }
    }

    const toggleConvert = () => {
        dispatch({type:"converting"})
    }

    const onChangeDisplayMode = (e:Mp.ConfigChangeEvent) => {
        dispatch({type:"fitToWindow", value:e.config.video.fitToWindow})
        changeVideoSize(e.config);
    }

    const close = () => {
        window.api.send("close", {mediaState:$appState.media});
    }

    const prepare = (e:Mp.ReadyEvent) => {

        dispatch({type:"isMaximized", value:e.config.isMaximized})

        updateVolume(e.config.audio.volume);
        updateAmpLevel(e.config.audio.ampLevel)

        dispatch({type:"mute", value:e.config.audio.mute})

        dispatch({type:"fitToWindow", value:e.config.video.fitToWindow})
        dispatch({type:"playbackSpeed", value:e.config.video.playbackSpeed})
        dispatch({type:"seekSpeed", value:e.config.video.seekSpeed})

        initPlayer();

    }

    const load = (e:Mp.FileLoadEvent) => {
        if(e.currentFile.id){
            loadMedia(e)
        }else{
            initPlayer();
        }
    }

    const onMousemove = () => {
        showControl();
    };

    const onKeydown = (e:KeyboardEvent) => {

        if(e.ctrlKey && e.key === "r") e.preventDefault();

        if(e.key === "F5") return window.api.send("reload", {});

        if(e.key === "ArrowRight"){

            showControl();

            if(e.shiftKey){
                changeCurrentTime($appState.media.seekSpeed)
            }else{
                playFoward(Buttons.left);
            }

            return
        }

        if(e.key === "ArrowLeft"){

            showControl();

            if(e.shiftKey){
                changeCurrentTime(-$appState.media.seekSpeed)
            }else{
                playBackward(Buttons.left);
            }

            return
        }

        if(e.key === "ArrowUp"){
            showControl();
            updateVolume($appState.media.videoVolume + 0.01)
            return
        }

        if(e.key === "ArrowDown"){
            showControl();
            updateVolume($appState.media.videoVolume - 0.01)
            return
        }

        if(e.key === "Escape"){
            return exitFullscreen();
        }

        if(e.ctrlKey && e.key === "m"){
            return toggleMute();
        }

        if(e.key === "Enter"){
            return togglePlay();
        }

        return handleShortcut("Player", e);

    };

    const onResize = () => {
        changeVideoSize()
    };

    const onContextMenu = (e:MouseEvent) => {
        e.preventDefault()
        e.stopPropagation()
        window.api.send("open-player-context", {})
    }

    onMount(() => {

        window.api.receive("ready", prepare)
        window.api.receive("load-file", load)
        window.api.receive("toggle-play", togglePlay)
        window.api.receive("change-display-mode", onChangeDisplayMode)
        window.api.receive("restart", initPlayer)
        window.api.receive("before-trash", beforeDelete)
        window.api.receive("before-rename", beforeRename)
        window.api.receive("after-toggle-maximize", onWindowSizeChanged)
        window.api.receive("toggle-convert", toggleConvert)
        window.api.receive("change-playback-speed", changePlaybackSpeed)
        window.api.receive("change-seek-speed", changeSeekSpeed);
        window.api.receive("toggle-fullscreen", toggleFullscreen)
        window.api.receive("capture-media", captureMedia)
        window.api.receive("picture-in-picture", requestPIP)
        window.api.receive("log", data => console.log(data.log))

        return () => {

            window.api.removeAllListeners("ready")
            window.api.removeAllListeners("load-file")
            window.api.removeAllListeners("toggle-play")
            window.api.removeAllListeners("change-display-mode")
            window.api.removeAllListeners("restart")
            window.api.removeAllListeners("before-trash")
            window.api.removeAllListeners("before-rename")
            window.api.removeAllListeners("after-toggle-maximize")
            window.api.removeAllListeners("toggle-convert")
            window.api.removeAllListeners("change-playback-speed")
            window.api.removeAllListeners("change-seek-speed")
            window.api.removeAllListeners("toggle-fullscreen")
            window.api.removeAllListeners("capture-media")
            window.api.removeAllListeners("picture-in-picture")
            window.api.removeAllListeners("log")
        }
    })
</script>

<svelte:window on:keydown={onKeydown} on:resize={onResize}/>
<svelte:document on:mousemove={onMousemove}/>

<div class="player-viewport" class:full-screen={$appState.isFullScreen} class:loaded={$appState.loaded} class:autohide={$appState.autohide}>

    <div class="player-title-bar">
        <div class="icon-area">
            <img class="ico" src={icon} alt=""/>
            <span>{APP_NAME}</span>
        </div>
        <div class="title">{$appState.currentFile.name}</div>
        <div class="window-area">
            <div class="minimize" on:click={minimize} on:keydown={handleKeyEvent} role="button" tabindex="-1">&minus;</div>
            <div class="maximize" on:click={toggleMaximize} on:keydown={handleKeyEvent} role="button" tabindex="-1">
                <div class:minbtn={$appState.isMaximized} class:maxbtn={!$appState.isMaximized}></div>
            </div>
            <div class="close" on:click={close} on:keydown={handleKeyEvent} role="button" tabindex="-1">&times;</div>
        </div>
    </div>

    <div bind:this={container} class="video-container" on:dragover={e => e.preventDefault()} on:drop={onFileDrop} on:dblclick={togglePlay} on:contextmenu={onContextMenu} role="button" tabindex="-1">
        <video
            bind:this={video}
            class="video"
            src={$appState.currentFile.src}
            on:loadeddata={onMediaLoaded}
            on:ended={() => changeFile(FORWARD)}
            on:timeupdate={onTimeUpdate}
            on:play={onPlayed}
            on:pause={onPaused}
            on:contextmenu={onContextMenu}
            muted={$appState.media.mute}
        />
    </div>

    <Footer
        onMouseEnter={showControl}
        onUpdateTime={updateTime}
        onUpdateVolume={updateVolume}
        onUpdateAmpLevel={updateAmpLevel}
        onClickPlay={togglePlay}
        onClickStop={stop}
        onClickPrevious={playBackward}
        onClickNext={playFoward}
        onClickMute={toggleMute}
        t={t}
    />

</div>
