// src/renderer/playlist/list.tsx

type ListProps = {
    playlingItemId:string;
    files:Mp.MediaFile[],
    selection:Mp.PlaylistItemSelection;
    sortType:Mp.SortType;
    onFileListItemClicked:(e:React.MouseEvent) => void;
    onDragStart:(e:React.DragEvent) => void;
    onDragEnter:(e:React.DragEvent) => void;
    onDragEnd:(e:React.DragEvent) => void;
}

export const List = (props:ListProps) => {

    const createListItem = (file:Mp.MediaFile) => {

        return (
            <div
                key={file.id}
                title={file.name}
                id={file.id}
                draggable="true"
                className={`playlist-item ${props.playlingItemId === file.id ? "current" : ""} ${props.selection.selectedIds.includes(file.id) ? "selected" : ""}`}
                data-dir={encodeURIComponent(file.dir)}
                onDoubleClick={props.onFileListItemClicked}
                onDragStart={props.onDragStart}
                onDragEnter={props.onDragEnter}
                onDragEnd={props.onDragEnd}
            >{file.name}</div>
        )
    }

    const createSeparator = (file:Mp.MediaFile) => {

        return (
            <div key={encodeURIComponent(file.dir)} className="group separator" title={file.dir} id={encodeURIComponent(file.dir)}>
                <div className="left separator"></div>
                <div className="mid separator">{file.dir}</div>
                <div className="right separator"></div>
            </div>
        );
    }

    const renderPlaylistItems = () => {

        const items:JSX.Element[] = [];

        let key = ""

        props.files.forEach(file => {

            if(file.dir != key){
                key = file.dir;
                items.push(createSeparator(file))
            }

            items.push(createListItem(file))

        })

        return items;
    }

    return (
        <div key="fileList" id="fileList" className={`file-list ${props.sortType.groupBy ? "group-by" : "" }`}>{renderPlaylistItems()}</div>
    )
}

// src/renderer/playlist/List.svelte
<script lang="ts">
    import { afterUpdate } from "svelte";
    import { appState, dispatch } from "./appStateReducer";

    export let onMouseDown:(e:MouseEvent) => void;
    export let scrollToElement:(id:string) => void;
    export let getChildIndex:(id:string | null | undefined) => number;

    afterUpdate(() => {
        if($appState.updateType === "Append" && $appState.playlingItemId){
            scrollToElement($appState.playlingItemId)
        }
    })

    const onFileListItemClicked = (e:MouseEvent) => {
        const index = getChildIndex((e.target as HTMLElement).id);
        window.api.send("load-file", {index, isAbsolute:true});
    }

    const startDragPlaylistItem = (e:DragEvent) => {
        if(!e.target || !(e.target instanceof HTMLElement)) return;

        e.stopPropagation();
        dispatch({type:"startDrag", value:{startId:e.target.id, dir:e.target.getAttribute("data-dir") ?? ""}})
    }

    const toggleHighlightDropTarget = (e:DragEvent) => {

        if(!$appState.dragState.dragging) return;

        if(!e.target || !(e.target instanceof HTMLElement)) return;

        if($appState.dragState.dir !== e.target.getAttribute("data-dir")){
            $appState.dragState.targetId = "";
            return;
        }

        dispatch({type:"drag", value:e.target.id})

    }

    const endDragPlaylistItem = (_e:DragEvent) => {

        if(!$appState.dragState.dragging) return;

        if($appState.dragState.targetId){

            window.api.send("change-playlist-order", {
                start:getChildIndex($appState.dragState.startId),
                end:getChildIndex($appState.dragState.targetId),
                currentIndex:getChildIndex($appState.playlingItemId),
                type:"Move"
            });

        }

        dispatch({type:"endDrag"})
    }


</script>

<div id="fileList" class="file-list" class:grou-by={$appState.sortType.groupBy}>

    {#each $appState.files as file, index}

        {#if index == 0 || $appState.files[index - 1].dir != $appState.files[index].dir }
            <div class="group separator" title={file.dir} id={encodeURIComponent(file.dir)}>
                <div class="left separator"></div>
                <div class="mid separator">{file.dir}</div>
                <div class="right separator"></div>
            </div>
        {/if}

        <div
            title={file.name}
            id={file.id}
            draggable="true"
            class="playlist-item"
            class:current={$appState.playlingItemId === file.id}
            class:selected={$appState.selection.selectedIds.includes(file.id)}
            class:draghover={$appState.dragState.targetId == file.id}
            data-dir={encodeURIComponent(file.dir)}
            on:mousedown={onMouseDown}
            on:dblclick={onFileListItemClicked}
            on:dragstart={startDragPlaylistItem}
            on:dragenter={toggleHighlightDropTarget}
            on:dragend={endDragPlaylistItem}
            role="button"
            tabindex="-1"
        >{file.name}</div>

    {/each}
</div>
